export const DEMO_SESSION = {
  userId: 'demo-client-001',
  email: 'emma@example.com',
  name: 'Emma Thompson',
  role: 'CLIENT' as const,
}

export const DEMO_APPOINTMENTS = [
  {
    id: 'apt-1',
    title: 'Nutrition Consultation',
    date: '2026-07-08',
    time: '10:00',
    duration: 60,
    status: 'CONFIRMED',
    notes: 'Please bring your 3-day food journal',
    zoomLink: 'https://zoom.us/j/example',
    clientId: 'demo-client-001',
    coachId: 'coach-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'apt-2',
    title: 'Gut Health Review',
    date: '2026-07-22',
    time: '11:00',
    duration: 60,
    status: 'CONFIRMED',
    notes: null,
    zoomLink: 'https://zoom.us/j/example2',
    clientId: 'demo-client-001',
    coachId: 'coach-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'apt-3',
    title: 'Follow-up Session',
    date: '2026-08-05',
    time: '09:30',
    duration: 45,
    status: 'PENDING',
    notes: null,
    zoomLink: null,
    clientId: 'demo-client-001',
    coachId: 'coach-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'apt-4',
    title: 'Initial Assessment',
    date: '2026-06-10',
    time: '10:00',
    duration: 90,
    status: 'COMPLETED',
    notes: 'Great first session!',
    zoomLink: null,
    clientId: 'demo-client-001',
    coachId: 'coach-001',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const DEMO_SYMPTOMS = [
  { id: 's1', weekDate: '2026-04-28', energy: 4, sleep: 5, digestion: 3, mood: 5, stress: 8, appetite: 6, bloating: 4, headaches: 6, hydration: 4, exercise: 20, notes: 'Feeling sluggish, lots of bloating after meals', clientId: 'demo-client-001', createdAt: new Date() },
  { id: 's2', weekDate: '2026-05-05', energy: 5, sleep: 5, digestion: 4, mood: 5, stress: 7, appetite: 6, bloating: 3, headaches: 5, hydration: 5, exercise: 30, notes: 'Slightly better this week', clientId: 'demo-client-001', createdAt: new Date() },
  { id: 's3', weekDate: '2026-05-12', energy: 5, sleep: 6, digestion: 5, mood: 6, stress: 7, appetite: 7, bloating: 3, headaches: 4, hydration: 6, exercise: 45, notes: 'Added more water, feeling some improvement', clientId: 'demo-client-001', createdAt: new Date() },
  { id: 's4', weekDate: '2026-05-19', energy: 6, sleep: 6, digestion: 5, mood: 6, stress: 6, appetite: 7, bloating: 3, headaches: 3, hydration: 7, exercise: 60, notes: 'Energy is improving!', clientId: 'demo-client-001', createdAt: new Date() },
  { id: 's5', weekDate: '2026-05-26', energy: 6, sleep: 7, digestion: 6, mood: 7, stress: 5, appetite: 7, bloating: 2, headaches: 3, hydration: 7, exercise: 75, notes: 'Sleep is getting much better', clientId: 'demo-client-001', createdAt: new Date() },
  { id: 's6', weekDate: '2026-06-02', energy: 7, sleep: 7, digestion: 7, mood: 7, stress: 5, appetite: 8, bloating: 2, headaches: 2, hydration: 8, exercise: 90, notes: 'Feeling really good this week!', clientId: 'demo-client-001', createdAt: new Date() },
  { id: 's7', weekDate: '2026-06-09', energy: 7, sleep: 8, digestion: 7, mood: 8, stress: 4, appetite: 8, bloating: 1, headaches: 1, hydration: 8, exercise: 90, notes: 'Best week yet. Gut feels great.', clientId: 'demo-client-001', createdAt: new Date() },
  { id: 's8', weekDate: '2026-06-16', energy: 8, sleep: 8, digestion: 8, mood: 8, stress: 4, appetite: 8, bloating: 1, headaches: 1, hydration: 9, exercise: 120, notes: 'Incredible progress — energy through the roof!', clientId: 'demo-client-001', createdAt: new Date() },
]

export const DEMO_MESSAGES = [
  { id: 'm1', senderId: 'coach-001', recipientId: 'demo-client-001', content: 'Hi Emma! Welcome to the Rooted & Nourished portal. I\'m so excited to work with you on your health journey. Please fill out your intake form when you get a chance — it helps me understand your background before our first session.', read: true, createdAt: new Date('2026-06-10T10:00:00'), sender: { name: 'Sophia Khosravi', role: 'COACH' } },
  { id: 'm2', senderId: 'demo-client-001', recipientId: 'coach-001', content: 'Hi Sophia! Thank you so much, I just submitted my intake form. I\'m really looking forward to our first session. I\'ve been struggling with bloating and low energy for a while now.', read: true, createdAt: new Date('2026-06-10T14:30:00'), sender: { name: 'Emma Thompson', role: 'CLIENT' } },
  { id: 'm3', senderId: 'coach-001', recipientId: 'demo-client-001', content: 'I reviewed your intake form — thank you for being so thorough! I can see a strong connection between your symptoms and some dietary patterns. I\'ve got some great ideas for our session. See you Tuesday! 🌿', read: true, createdAt: new Date('2026-06-11T09:00:00'), sender: { name: 'Sophia Khosravi', role: 'COACH' } },
  { id: 'm4', senderId: 'demo-client-001', recipientId: 'coach-001', content: 'Quick question — should I keep a food diary before our next session? I noticed that my symptoms are worse after eating gluten.', read: true, createdAt: new Date('2026-06-23T16:00:00'), sender: { name: 'Emma Thompson', role: 'CLIENT' } },
  { id: 'm5', senderId: 'coach-001', recipientId: 'demo-client-001', content: 'Yes! That\'s a great observation Emma. Please track your meals for 3 days and note any symptoms within 2 hours of eating. A food diary will really help us identify your triggers. Keep it simple — just jot down what you eat, the time, and how you feel. 📝', read: false, createdAt: new Date('2026-06-24T10:00:00'), sender: { name: 'Sophia Khosravi', role: 'COACH' } },
]

export const DEMO_RECORDS = [
  {
    id: 'r1',
    clientId: 'demo-client-001',
    coachId: 'coach-001',
    appointmentId: 'apt-4',
    notes: 'Emma presented with chronic fatigue, bloating, and brain fog for approximately 2 years. History of antibiotic use and high-stress job. Suspect leaky gut and potential gluten sensitivity. Good candidate for elimination protocol.',
    recommendations: '1. Begin 3-week elimination diet removing gluten, dairy, and processed sugar\n2. Add a high-quality probiotic (Lactobacillus acidophilus + Bifidobacterium) with meals\n3. Increase water intake to 8 glasses/day\n4. Add 1 tbsp of apple cider vinegar in water before main meals\n5. Prioritize 7-8 hours of sleep — aim for consistent sleep/wake times',
    createdAt: new Date('2026-06-10T12:00:00'),
    updatedAt: new Date('2026-06-10T12:00:00'),
    appointment: { title: 'Initial Assessment', date: '2026-06-10', time: '10:00', duration: 90, id: 'apt-4', clientId: 'demo-client-001', coachId: 'coach-001', status: 'COMPLETED', notes: null, zoomLink: null, createdAt: new Date(), updatedAt: new Date() },
  },
]

export const DEMO_FORM = {
  id: 'f1',
  type: 'INTAKE',
  submittedAt: new Date('2026-06-10T08:00:00'),
  data: JSON.stringify({
    dob: '1992-03-15',
    gender: 'Female',
    height: "5'6\"",
    weight: '148 lbs',
    occupation: 'Marketing Manager',
    referral: 'Instagram',
    diagnoses: 'IBS (self-diagnosed), occasional anxiety',
    medications: 'Magnesium glycinate 400mg nightly',
    surgeries: 'None',
    familyHistory: 'Mother — Type 2 diabetes, thyroid issues',
    currentSymptoms: ['Fatigue', 'Bloating', 'Brain fog', 'Constipation', 'Anxiety', 'Insomnia/poor sleep'],
    worstSymptom: 'Bloating and fatigue — I feel exhausted after every meal and my stomach is always distended by evening.',
    symptomDuration: 'About 2 years, but worse in the past 6 months',
    typicalDiet: 'Breakfast: granola with oat milk. Lunch: sandwich or salad with dressing. Dinner: pasta or rice dishes, sometimes takeout. Snacks: crackers, protein bars.',
    dietaryRestrictions: [],
    waterIntake: '4',
    exerciseFrequency: '1–2x/week',
    sleepQuality: 'Poor',
    stressLevel: '8',
    healthGoals: 'Reduce bloating and digestive discomfort, increase energy levels, lose 10-15 lbs, improve sleep quality, and understand what foods are triggering my symptoms.',
    successVision: 'Waking up with energy, not feeling bloated after meals, having mental clarity at work, and feeling comfortable in my body again.',
    barriers: 'Busy schedule makes it hard to cook. I tend to stress eat. Past diets have felt too restrictive and I always fall off.',
    additionalNotes: 'I\'ve tried elimination diets before but found them too hard to follow alone. I really hope having a coach will make the difference this time.',
  }),
  clientId: 'demo-client-001',
}
